### PR TITLE
Lawal Habeeb Update assignment.md

### PR DESCRIPTION
**Pull request by Starrz09**

### CODE REVIEW

**Comment by jlooper** [comment]
We aren't looking for PRs for the solution to this repo; rather, please solve the problems on your own and chat about them in the discussion board. Thanks!

**Comment by Starrz09** [comment]
Hi, please if I'm to understand you well, you meant, I shouldn't provide
the answers on the platform, rather I should solve them and provide the
answers to myself and probably discuss it on the group right?

**Comment by jlooper** [comment]
Correct

**Comment by Starrz09** [comment]
Got it, thanks!

**Pull request closed without merging**
