### PR TITLE
Create README.hi.md

### PR DESCRIPTION
**Pull request by AdityaGarg00**
created readme hindi

### CODE REVIEW

**Comment by vishvanathan-k** [comment]
@AdityaGarg00 would you mind drafting the PR till you are finished??

**Comment by AdityaGarg00** [comment]
@vishvanathan-k  I am done with this file and i am unable to find any issues please let me know if you see any issues with this particular file

**Comment by vishvanathan-k** [comment]
Wait are you sure?!? It seems too short than it should be, You have missed some !!

**Comment by vishvanathan-k** [comment]
Oh!! But you have to translate all the readme files in the repo, that's totally 48 tasks !!

**Comment by AdityaGarg00** [comment]
oh ok I'll do that

**Comment by paladique** [comment]
@AdityaGarg00 thank you! It's not a requirement to translate everything, but @vishvanathan-k  if you're a native speaker as well we'd love to have some contributions, checkout what's left in the Issue #146

**Comment by vishvanathan-k** [comment]
@paladique Sorry I am not a native speaker, but I have studied some hindi, maybe I could review hindi translations if you want me to... .I am terrible in English to Hindi, but decent enough the other way around

**Review by Fats-eficity — APPROVED** [review]

**Pull request merged**
