### PR TITLE
[sv-SE] translation swedish

### PR DESCRIPTION
**Pull request by softchris**

### CODE REVIEW

**Comment by jlooper** [comment]
maybe convert to draft while u go?

**Comment by Willdee863** [comment]
Thanks

**Comment by Willdee863** [comment]
Hey

**Comment by Willdee863** [comment]
> Thanks

Hey

**Comment by jlooper** [comment]
> Hey

@Willdee863 please do not spam this repo

**Comment by Willdee863** [comment]
> Thanks

Thanks

**Comment by Willdee863** [comment]
Yes

**Comment by Willdee863** [comment]
Yes

**Pull request closed without merging**
