### PR TITLE
Translation of the Main repo README to pt-PT

### PR DESCRIPTION
**Pull request by Midas-sudo**

### CODE REVIEW

**Review by paladique — CHANGES_REQUESTED** [review]
Thanks for your translation! Before I can merge this, can you verify that there are no broken links or images? [You can check it here](https://github.com/microsoft/Data-Science-For-Beginners/blob/0292a5ce2fc8e7aad2abb951317746dd6c4fcf2d/translations/README.pt-pt.md)

**Comment by Midas-sudo** [comment]
@paladique I thinks thats fixed. Hopefully i didnt miss any link. 😅

**Comment by Midas-sudo** [comment]
> Thanks for your translation! Before I can merge this, can you verify that there are no broken links or images? [You can check it here](https://github.com/microsoft/Data-Science-For-Beginners/blob/0292a5ce2fc8e7aad2abb951317746dd6c4fcf2d/translations/README.pt-pt.md)


@paladique I thinks thats fixed. Hopefully i didnt miss any link. 😅

**Review by paladique — APPROVED** [review]

**Comment by paladique** [comment]
@Midas-sudo thank you!

**Pull request merged**
