### PR TITLE
[ko-Korea] translation Korean (Chapter 4)

### PR DESCRIPTION
**Pull request by nahyeong99**
[#197] 

- [ ] Data Science Lifecycle base README
    - [X] Introduction README
    - [ ] Introduction assignment
    - [x] Analyzing README
    - [x] Analyzing assignment
    - [x] Communication README
    - [ ] Communication assignment

Thank you.

### CODE REVIEW

**Comment by SoniaComp** [comment]
Hi! 👋 It seems that some of your PRs overlap with my Draft. 
Could you check the draft #157 ? 🙏

**Comment by nahyeong99** [comment]
> Hi! 👋 It seems that some of your PRs overlap with my Draft. Could you check the draft #157 ? 🙏
> 
> I've already done the below, so could you please proceed without these? Your reviews and comments on the PR below are always welcome. 😊
> 
> * Introduction base README
> * Defining Data Science README
> * Ethics README

I didn't know it was done because in the issue report, it's not updated. Sorry about that, and I think It's better for me to translate chapter4 rather than chapter1. You'll be able to translate chapter1. Thank you!

**Comment by SoniaComp** [comment]
Thank you so much and sorry for confusion.
Ok! I'll keep going on chapter1.  Thank you! 😊

**Comment by nahyeong99** [comment]
> @SoniaComp @nahyeong99 I will assign you two to #197 so you can check them off as you go :). Thanks!

Thank you!

**Comment by nahyeong99** [comment]
@paladique Sir, I check for it... but I think you forgot to assign me! Can you please check it one more time? 😂

**Comment by paladique** [comment]
@nahyeong99 hey there! Happy to add you! Can you add a comment to #197? You have to interact with it for me to assign you 🙂

**Comment by nahyeong99** [comment]
#197

**Pull request merged**
