### PR TITLE
Add Pandas in R Lesson

### LINKED ISSUE #138: [Lesson] R
Take the lesson on [Python and Pandas](https://github.com/microsoft/Data-Science-For-Beginners/tree/main/2-Working-With-Data/07-python) and create its R counterpart.

Add this as a bonus lesson in the Working with Data  directory

### PR DESCRIPTION
**Pull request by keshav340**
This fixes #138 

Creating a R version of Pandas lesson

### CODE REVIEW

**Comment by keshav340** [comment]
Review my changes, if anything I have to add please tell me.

**Comment by keshav340** [comment]
Review my changes,if anything I have to add please tell me.

**Comment by jlooper** [comment]
hi, this folder is in the wrong place; any R folder should be associated to a particular lesson. Which lesson is this aligning to?

**Comment by keshav340** [comment]
@jlooper  As you had mentioned in the issue take the lesson on python and pandas and create its R counterpart and add this lesson in Working with Data Directory.

**Comment by jlooper** [comment]
hi, almost there!

Please edit the following:
- just name the folder 'R' with no other text
- add explanations of the code via markdown as in the notebook for Python
- name the file `notebook.ipynb` without the capitalization
- remove unused codeblocks at the bottom
- make sure there are no errors or warnings in the file; right now there are some of these if you view in browser

**Comment by paladique** [comment]
@keshav340 thank you for your contribution! I added some details what this PR is doing

**Pull request merged**
