### PR TITLE
added assignment for low code translated in russian

### PR DESCRIPTION
**Pull request by kavinplays**
#139

### CODE REVIEW

**Comment by paladique** [comment]
@kavinplays thanks! Since this is your first translation, we will have another person double check it. @fortis3000 since you have been doing translations, would you be able to verify this one? Your help would be appreciated, thank you!

**Comment by fortis3000** [comment]
Hi @paladique! It's an honour for me to verify someone's translation. I found a number of critical issues, e.g. non-localized titles, mixing up Russian letters. I suppose it would be great to apply more effort to this translation.

@kavinplays, some hints: 
* try not to use automatic translators
* try to localize material not just translate
* follow the first pieces of translations (apparently my) to be consistent with the whole course

**Comment by kavinplays** [comment]
Hi, I am not a native russian speaker and have been learning it during lockdown, sorry for the mistakes I made, I did this to force myself to learn some new words. I will look at one of your translations and up, thanks for checking it.

**Comment by jlooper** [comment]
Since it seems that these translations were problematic, I will close this PR

**Pull request closed without merging**
